# Generated by Django 4.1.5 on 2023-01-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecins',
            options={'verbose_name': 'Medecin', 'verbose_name_plural': 'Medecins'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AddField(
            model_name='medecins',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='prefession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medecins.profession'),
        ),
        migrations.AddField(
            model_name='medecins',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
